export const BACKEND_IP_ENV_KEY = 'BACKEND_IP';
export const CAPITAL_API_KEY_ENV_KEY = 'CAPITAL_API_KEY';
export const CAPITAL_IDENTIFIER_ENV_KEY = 'CAPITAL_IDENTIFIER';
export const CAPITAL_PASSWORD_ENV_KEY = 'CAPITAL_PASSWORD';